# Topic 6: Linear Algebra with NumPy

In [1]:
import numpy as np

## Task 1

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

A.dot(B)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

## Task 2

In [4]:
A = np.array([
    [2, 5, 3],
    [1, -2, -1],
    [1, 3, 4]
])

def det_cal(arr):
    return np.linalg.det(arr)

det_cal(A)

np.float64(-20.000000000000007)

## TAsk 3

In [7]:
A = np.array([
    [1, 2, 3, 4],
    [0, 1, 2, 3],
    [4, 0, 1, 2],
    [3, 4, 0, 1]
])
def calc_inv(A):
    det_a= np.linalg.det(A)
    if np.isclose(det_a,0):
        print("Its singular")
        return None
    return np.linalg.inv(A)
calc_inv(A)

array([[ 2.00000000e-01, -4.00000000e-01,  2.00000000e-01,
        -4.16333634e-17],
       [ 2.00000000e-01, -2.00000000e-01, -2.00000000e-01,
         2.00000000e-01],
       [ 2.00000000e+00, -2.40000000e+00, -2.00000000e-01,
        -4.00000000e-01],
       [-1.40000000e+00,  2.00000000e+00,  2.00000000e-01,
         2.00000000e-01]])

## Task  4

In [10]:
# Coefficient matrix
A = np.array([[2, 3],
              [3, 4]])

# Right-hand side constants
B = np.array([8, 11])
X=np.linalg.solve(A,B)
print(X)
print("checking")
A@X

[1. 2.]
checking


array([ 8., 11.])

## Task 5

In [13]:
A = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
])
eigenval, eigenvector=np.linalg.eigh(A)
eigenval, eigenvector

(array([0.58578644, 2.        , 3.41421356]),
 array([[-5.00000000e-01, -7.07106781e-01,  5.00000000e-01],
        [-7.07106781e-01,  4.37150316e-16, -7.07106781e-01],
        [-5.00000000e-01,  7.07106781e-01,  5.00000000e-01]]))

## Task 6

In [14]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
U, S, VT = np.linalg.svd(A)

print("U:", U)
print("Singular Values:", S)
print("V^T:", VT)

U: [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular Values: [9.52551809 0.51430058]
V^T: [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


## Task 7

In [15]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
np.linalg.matrix_rank(A)

np.int64(2)

## Task 8

In [17]:
vec1 = np.random.rand(3)
vec2 = np.random.rand(3)
print(vec1)
print(vec2)

print(vec1.dot(vec2))
print(np.cross(vec1, vec2))

[0.40005896 0.80915313 0.26019025]
[0.92465708 0.22166758 0.67938877]
0.7260506994650872
[ 0.4920538  -0.03120881 -0.65950907]
