# Topic 2 :Array Indexing, Slicing, & Reshaping

In [1]:
import numpy as np

### Task 1

In [13]:
arr=np.random.randint(1,100,36).reshape(6,6)
print(arr)
# second row
arr[1]
# last two column
arr[:,4:]
#diagonal elmement
arr.diagonal()

[[63 17 29 47 63 10]
 [83 11 82 76 83 65]
 [29 77 68 61 44 63]
 [70 94 10 67 70 35]
 [56 42 90 75 14 72]
 [61 27 50 37 21  7]]


array([63, 11, 68, 67, 14,  7])

### Task 2

In [16]:
arr=np.arange(1,51).reshape(5,10)
print(arr)
arr[:3]

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

### Task 3

In [21]:
arr=np.arange(64).reshape(4,4,4)
print(arr)
arr[1:3]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


array([[[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

### TAsk 4

In [26]:
def rev_arr(arr):
    return arr[::-1]
arr=np.arange(10)
arr
rev_arr(arr)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Task 5

In [30]:
arr=np.arange(16).reshape(4,4)
print(arr)
arr[[0,-1]]=arr[[-1,0]]
arr

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

### Task 6

In [ ]:
arr_1=np.arange(18).reshape(3,6)
print(arr_1.itemsize)
arr_2=arr_1.reshape(2,9)
print(arr_2.itemsize)

# reshaping just change the veiw no internal memory size

8
8


### TAsk 7

In [37]:
arr = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr[arr>20]

array([25, 30, 35, 40, 45])

### Task 8

In [39]:
arr=np.arange(8).reshape(4,2)
print(arr)
def tranpose(arr):
    return arr.T
tranpose(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


array([[0, 2, 4, 6],
       [1, 3, 5, 7]])