# Topic 1 : Creating Arrays

In [2]:
import numpy as np

### Task 1

In [3]:
arr=np.arange(1, 21).reshape(4, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Task 2

In [4]:
arr = np.random.random(25).reshape(5,5)
arr

array([[0.11848811, 0.52641251, 0.66084021, 0.94688549, 0.44139489],
       [0.84429914, 0.93675029, 0.11061424, 0.73576066, 0.88231972],
       [0.84667285, 0.10100396, 0.72284178, 0.2380936 , 0.75346864],
       [0.59139036, 0.74648709, 0.78060522, 0.48878418, 0.15412192],
       [0.96023039, 0.68965167, 0.99850797, 0.37116933, 0.9852989 ]])

### Task 3

In [6]:
def np_array_creation(arr):
    try:
        np_array=np.array(arr)
        return np_array
    except Exception as e:
        print(e)
        return None
flat = [1, 2, 3, 4]
print(np_array_creation(flat))

nested = [[1, 2], [3, 4]]
print(np_array_creation(nested))

jagged = [[1, 2], [3, 4, 5]]
print(np_array_creation(jagged))

[1 2 3 4]
[[1 2]
 [3 4]]
setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
None


### Task 4

In [11]:
np.identity(36)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

### TAsk 5

In [13]:
lin_arr=np.linspace(-5, 5, 10)
print(lin_arr)
arrange_arr=np.arange(-5,5)
arrange_arr

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

- arrange is used when we are not sure about the number of points but we have stepsize
- linespace is used when you are sure about the number of poits

- arrange increase the value of point by stepsize
- linespace used the formula stepsize=(end-start)n-1

### Task 6

In [15]:
np.random.randint(10, 50, 27).reshape(3,3,3)

array([[[26, 40, 13],
        [37, 10, 23],
        [39, 15, 30]],

       [[49, 40, 44],
        [25, 22, 11],
        [16, 32, 24]],

       [[44, 38, 11],
        [23, 41, 12],
        [15, 48, 14]]])

### Task 7

In [17]:
np.random.randint(0,2,16).reshape(4,4)

array([[0, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [0, 1, 1, 1]])

### Task 8

In [22]:
arr=np.random.randint(1,1000,100)
arr.mean()
arr.sum()
arr.min()
arr.max()

np.int64(980)