# Topic 5 :Working with Missing Data in NumPy

In [1]:
import numpy as np

## Task 1

In [2]:

arr = np.array([1.0, 2.5, np.nan, 4.7, np.nan, 6.0])
np.isnan(arr)

array([False, False,  True, False,  True, False])

## TAsk 2

In [3]:
arr = np.array([1.0, 2.5, np.nan, 4.7, np.nan, 6.0])
arr_mod=np.where(np.isnan(arr),-1, arr )
arr, arr_mod

(array([1. , 2.5, nan, 4.7, nan, 6. ]),
 array([ 1. ,  2.5, -1. ,  4.7, -1. ,  6. ]))

## Task 3

In [4]:
arr = np.array([
    [1.0, 2.0, 3.0],
    [4.0, np.nan, 6.0],
    [7.0, 8.0, 9.0],
    [np.nan, 11.0, 12.0]
])

def remove_nan(arr):
    return arr[~np.isnan(arr).any(axis=1)]

clean_arr=remove_nan(arr)
clean_arr

array([[1., 2., 3.],
       [7., 8., 9.]])

## Task 4

In [5]:
arr = np.array([1.0, np.nan, 3.0, np.nan, 5.0, 6.0])
print(arr)
def interpolate_arr(arr):
    nans=np.isnan(arr)
    indices=np.arange(len(arr))
    arr[nans]=np.interp(indices[nans], indices[~nans],arr[~nans])
    return arr

inte_arr=interpolate_arr(arr)
inte_arr

[ 1. nan  3. nan  5.  6.]


array([1., 2., 3., 4., 5., 6.])

## Task 5

In [10]:
arr = np.array([np.nan, 1.0, np.nan, 3.0, np.nan, 5.0, 6.0, np.nan])
def forward_fill(arr):
    mask=np.isnan(arr)
    filled=arr.copy()
    # print(filled[~mask])
    index=np.arange(len(filled))
    # filled[mask]= filled[~mask][np.minimum.accumulate(np.where(~mask, index, 0 ))]
    # print(np.where(~mask, index, 0))
    ff_mimic=np.maximum.accumulate(np.where(~mask, index, 0))
    print(ff_mimic)
    # print(filled[~mask][ff_mimic])
    # filled[mask]=filled[~mask][np.maximum.accumulate(np.where(~mask, index, 0))]
    filled[mask] = filled[np.maximum.accumulate(np.where(~mask, index, 0))][mask]
    

    return filled

def backward_fill(arr):
    mask = np.isnan(arr)
    filled = arr.copy()
    index = np.arange(len(arr))

    select_index = np.where(~mask, index, len(arr)-1)
    
    bb_mmic = np.minimum.accumulate(select_index[::-1])[::-1]
    
    filled[mask] = filled[bb_mmic][mask]
    
    return filled

forward_fill(arr)
print(arr)
backward_fill(arr)

[0 1 1 3 3 5 6 6]
[nan  1. nan  3. nan  5.  6. nan]


array([ 1.,  1.,  3.,  3.,  5.,  5.,  6., nan])

## Task 6

In [14]:
arr = np.array([10, 12, 13, 12, 14, 13, 15, 120]) 
def detect_outler(arr):
    q1=np.percentile(arr,25)
    q3=np.percentile(arr,75)
    iqr=q3-q1
    lower_bound=q1-1.5*iqr
    upper_bound=q3+1.5*iqr
    outliers=arr[(arr<lower_bound) | (arr>upper_bound)]
    return outliers
detect_outler(arr)

array([120])

## Task 7

In [17]:
arr = np.array([
    [1.0, 2.0, np.nan],
    [4.0, np.nan, 6.0],
    [7.0, 8.0, 9.0],
    [np.nan, 5.0, 3.0]
])

col_median=np.nanmedian(arr, axis=0)
print(col_median)
arr=np.where(np.isnan(arr), col_median, arr)
arr

[4. 5. 6.]


array([[1., 2., 6.],
       [4., 5., 6.],
       [7., 8., 9.],
       [4., 5., 3.]])