# Topic 3 :Broadcasting & Vectorized Operations

In [1]:
import numpy as np

## Task 1

In [2]:
arr1=np.arange(9).reshape(3,3)
arr2=np.arange(9).reshape(3,3)
arr1+arr2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

## Task 2

In [4]:
arr1=np.arange(9).reshape(3,3)
print(arr1)
arr1*[1,2,3]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

## Task 3

In [5]:
arr1=np.arange(9).reshape(3,3)
arr2=np.arange(3)
arr2+arr1

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

## Task 4

In [7]:
arr1=np.arange(9).reshape(3,3)
arr2=np.arange(9,12).reshape(3,)
arr1*arr2

array([[ 0, 10, 22],
       [27, 40, 55],
       [54, 70, 88]])

## Task 5

In [8]:
arr1=np.arange(9).reshape(3,3)
arr2=np.arange(9).reshape(3,3)
arr2.dot(arr1)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

## Task 6

In [9]:
arr=np.arange(25).reshape(5,5)
np.where(arr>15, arr**2, arr)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Task 7

In [12]:
arr=np.zeros(9).reshape(3,3)
print(arr)
arr2=np.arange(3).reshape(1,3)
print(arr2)
arr+arr2

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 1 2]]


array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

## Task 8

In [17]:
arr=np.arange(25).reshape(5,5)
print(arr)
arr.mean(axis=0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([10., 11., 12., 13., 14.])

# Task 9

cosine_similarity(A,B)= 
∥A∥⋅∥B∥
A⋅B
​


In [19]:
def cosine_simi(arr1,arr2):
    dot=np.dot(arr1,arr2)
    mag_arr1=np.linalg.norm(arr1)
    mag_arr2=np.linalg.norm(arr2)
    return dot/(mag_arr1*mag_arr2)

arr1=np.arange(9)
arr2=np.arange(9)
cosine_simi(arr1,arr2)


np.float64(0.9999999999999999)